K8s: ngnix working
Using init container with overridden startup.sh
All config is in cm.mira-config-dev.yaml

diff --git a/k8s/cm.mira-config-dev.yaml b/k8s/cm.mira-config-dev.yaml
--- a/k8s/cm.mira-config-dev.yaml
+++ b/k8s/cm.mira-config-dev.yaml
@@ -7,4 +7,33 @@ data:
   POSTGRES_USER: mirauser
   DB_HOST: postgres
   DJANGO_DEBUG: "True"
+  nginx.conf: |
+    server {
+        listen 80;
+        server_name mira.intuitem.com;
 
+        location = /favicon.ico { access_log off; log_not_found off; }
+        location /static/ {
+            root /usr/share/nginx/;
+        }
+
+        location / {
+            proxy_set_header Host $host;
+            proxy_pass http://localhost:8000;
+        }
+    }
+  startup.sh: |
+    #!/usr/bin/env bash
+    # wait for database to be ready
+    while ! python manage.py showmigrations iam > /dev/null 2>&1; do 
+    echo "database not ready; waiting"
+    sleep 10
+    done
+
+    python manage.py makemigrations cal core iam
+    python manage.py migrate
+    python manage.py makemessages -i venv -l fr
+    python manage.py compilemessages -i venv -l fr
+    # the next command will fail if already created, this is assumed
+    python manage.py createsuperuser --email root@example.com --noinput
+    python manage.py collectstatic --no-input --clear
